### ISSUE TITLE
Unnable to build project from downloaded sources

### ISSUE THREAD

**Issue by jDekx** [heuermh/velocity-cli#6]
Hello. 
git-commit-id-plugin prevents building project from downloaded sources: it wants .git directory.

`[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.2:revision (default) on project velocity-cli: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]`

Removing whole `<plugin>` tag worked for me, but it would be better not to run this plugin if .git directory does not exist. A build profile with proper `activation` could work, I think.

Thanks.

**Comment by heuermh** [comment]
Hello @jDekx, thank you for submitting this issue!

> A build profile with proper `activation` could work, I think.

Yes, that might work.  I will also look to see if there might be a config parameter for `git-commit-id-plugin` to not fail if `.git` is not found.

**Comment by heuermh** [comment]
Woot!  Found just such a config parameter.

With the change, the build in a directory without `.git` succeeds.  The commit template variable is not replaced, however
```
$ ./target/appassembler/bin/velocity --about
velocity-cli 2.2-SNAPSHOT
Commit: ${git.commit.id}  Build: 2019-12-11
Copyright (c) 2014-2019 held jointly by the individual authors.
Licensed under Apache License, Version 2.0
```

**Comment by heuermh** [comment]
Thanks, @jDekx!  I'll cut a version 2.1.1 release to include this fix.
